SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_NEW_SPEED = 1.2

PLAYER_RADIUS = 15
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_MAX_BOOST = 100
PLAYER_BOOST_DRAIN_RATE = 50
PLAYER_BOOST_RECHARGE_RATE = 15
PLAYER_WEAPON_MAX_UPGRADE = 3

SHOT_RADIUS = 2

LIFE_RADIUS = 10
LIFE_MAX_NUM = 3

PARTICLE_LIFETIME = 0.5